#  Assignment 2:- Numpy Package

In [125]:
##Numpy ---Linear Algebra Library
##Numpy is incrediably fast.
##Because numpy is binding to C Library.
##Python:- single threaded language
##C :- is multithreaded language
## Arrays are faster than list.
##Identity Matrix(np.identity(5)) :- Diagonal element (i=j) 1
##np.eye(5)
##np.random.rand:-Uniform distribution over 0 & 1
##Normal Distribution:- Mean=Median=Mode , ex:-np.random.rand(5)
##Standard normal distribution:- Mean=Median=Mode=0, ex:- np.random.randn()
##Broadcasting of array :- if changes in subset of array then it will refect in the parent array also.
##Numpy support Broadcasting.
##Standard deviation:-  on an average how elements are deviated from average values.
##Ex. arr2d.std()
##for axis 0 is row and 1 is column
##fancy indexing arr[[1,4,7,9]]

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.75714754, 0.10328282, 0.86132685, 0.66264598, 0.80569138])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [20]:
np.random.randn(25)

array([-1.12449333, -0.0835656 , -0.44689365,  1.30489867, -1.24895884,
       -0.41467908, -0.00608309, -1.22608058, -0.3083088 ,  0.3381956 ,
        0.22742592, -0.2286956 ,  0.96811514, -0.23743417,  0.86309066,
        0.81128852, -0.28494857,  1.21968022,  0.32004475, -1.36958967,
       -1.11480858,  0.39423602, -0.5472912 ,  0.51228386,  0.43425475])

In [26]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [27]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [48]:
array1=np.arange(12,27).reshape(3,5)
array2=np.delete(array1,4,1)
array2

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [61]:
array2

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [62]:
array2[1,3]

20

In [64]:
array3=np.arange(1,26).reshape(5,5)
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [87]:
array3[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [88]:
array3[4:5]

array([[21, 22, 23, 24, 25]])

In [89]:
array3[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
array5=np.arange(1,26).reshape(5,5)
array5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [94]:
array5.sum()

325

In [95]:
array5.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [118]:
array6=array5.sum(1)
array6[0]

15

In [122]:
array5[:,4:5]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [124]:
array5.sum(0)

array([55, 60, 65, 70, 75])